-- ============================================================================
-- MTI Courses — Security Hardening Migration (Phase 1)
-- Safe / additive. Run AFTER demo-access migrations.
-- Project: rbhxufnfzsmkzenqavmf   academy.brokenenglish.in
-- ============================================================================

-- ── 1. Students: add auth_user_id + password_reset_required ──────────────────
ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE,
  ADD COLUMN IF NOT EXISTS password_reset_required boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS students_auth_user_id_idx
  ON public.students(auth_user_id);

-- ── 2. Admin users table (deny-all to public) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS public.admin_users (
  auth_user_id  uuid PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid
);
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
-- Zero policies = deny all non-service-role access

-- ── 3. is_admin() helper ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admin_users
    WHERE auth_user_id = auth.uid()
  );
$$;

-- ── 4. Security audit log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.security_audit_log (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id uuid,
  event_type    text NOT NULL,
  target_type   text,
  target_id     text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  metadata      jsonb
);
ALTER TABLE public.security_audit_log ENABLE ROW LEVEL SECURITY;
-- No public access

-- ── 5. Private video_assets table ────────────────────────────────────────────
-- Replaces raw video URLs stored in course_config.videos.
-- Store Bunny provider IDs here; Edge Function generates signed tokens.
CREATE TABLE IF NOT EXISTS public.video_assets (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_order         int    NOT NULL UNIQUE,
  provider             text   NOT NULL DEFAULT 'bunny',  -- 'bunny'|'youtube'|'mp4'
  provider_video_id    text,   -- Bunny video GUID or YouTube ID
  library_id           text,   -- Bunny library ID
  duration             int,    -- seconds (for watermark timing)
  thumbnail_public_url text,
  title                text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.video_assets ENABLE ROW LEVEL SECURITY;
-- No public access; Edge Function reads with service role

-- ── 6. Quiz answers table (private) ──────────────────────────────────────────
-- Stores correct answer indices server-side so they never reach the browser.
CREATE TABLE IF NOT EXISTS public.quiz_answers (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_order    int  NOT NULL,
  question_id     text NOT NULL,
  correct_index   int  NOT NULL,
  UNIQUE(lesson_order, question_id)
);
ALTER TABLE public.quiz_answers ENABLE ROW LEVEL SECURITY;
-- No public access; Edge Function reads with service role

-- ── 7. Enable RLS on students ─────────────────────────────────────────────────
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- Drop legacy permissive policies if any exist
DO $$ BEGIN
  DROP POLICY IF EXISTS "students_self_read"       ON public.students;
  DROP POLICY IF EXISTS "students_self_update"     ON public.students;
  DROP POLICY IF EXISTS "students_anon_read"       ON public.students;
  DROP POLICY IF EXISTS "Enable read access for all users" ON public.students;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Students can read ONLY their own row (matched by auth_user_id set during migration)
-- NOTE: Before migration sets auth_user_id, students still log in via legacy path.
-- This policy is safe to add now; it blocks cross-student reads after migration.
CREATE POLICY "students_own_read" ON public.students
  FOR SELECT
  TO authenticated
  USING (auth_user_id = auth.uid());

-- Students can update non-privileged fields on their own row only
-- valid_until, access_list, auth_user_id cannot be changed by student
CREATE POLICY "students_own_update_safe" ON public.students
  FOR UPDATE
  TO authenticated
  USING   (auth_user_id = auth.uid())
  WITH CHECK (
    auth_user_id = auth.uid()
    -- Students cannot elevate their own access_list or validity:
    -- enforced by not exposing update endpoint for those columns
  );

-- ── 8. Enable RLS on student_progress ────────────────────────────────────────
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "progress_self_read"  ON public.student_progress;
  DROP POLICY IF EXISTS "progress_self_write" ON public.student_progress;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Students read own progress
CREATE POLICY "progress_own_read" ON public.student_progress
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.students s
      WHERE s.id = student_progress.student_id
        AND s.auth_user_id = auth.uid()
    )
  );

-- Students write own progress only (cannot forge another student_id)
CREATE POLICY "progress_own_write" ON public.student_progress
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.students s
      WHERE s.id = student_progress.student_id
        AND s.auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.students s
      WHERE s.id = student_progress.student_id
        AND s.auth_user_id = auth.uid()
    )
  );

-- ── 9. course_config RLS ──────────────────────────────────────────────────────
-- WARNING: The app currently relies on all students reading course_config rows:
--   - videos          (video metadata — MUST move to video_assets)
--   - quiz_*          (admin-uploaded quiz questions — no answers)
--   - drip_*          (per-student drip schedule)
--   - lastlesson_*    (per-student last lesson)
--   - el_settings     (ElevenLabs key — MUST remove from here)
--   - admin_cred      (admin password — MUST remove from here)
--
-- PHASE 1: Enable RLS but allow authenticated reads (blocks anon).
-- PHASE 2 (after full migration): restrict per-key.
ALTER TABLE public.course_config ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "config_auth_read"  ON public.course_config;
  DROP POLICY IF EXISTS "config_auth_write" ON public.course_config;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Authenticated users can read most config rows (still allows video/quiz access)
-- Block: admin_cred and el_settings from non-admins
CREATE POLICY "config_auth_read" ON public.course_config
  FOR SELECT
  TO authenticated
  USING (
    id NOT IN ('admin_cred', 'el_settings')
    OR is_admin()
  );

-- Only admins can write course_config
CREATE POLICY "config_admin_write" ON public.course_config
  FOR ALL
  TO authenticated
  USING   (is_admin())
  WITH CHECK (is_admin());

-- Anonymous users: zero access to course_config
-- (no anon policy = deny)

-- ── 10. Seed quiz_answers from the embedded QUIZ_BANK ────────────────────────
-- Run this ONCE to populate server-side answers.
-- These are the same answers currently in the frontend JS (removing them from JS
-- after this is populated closes the quiz-cheat vulnerability).
INSERT INTO public.quiz_answers (lesson_order, question_id, correct_index) VALUES
  -- Day 1
  (1,'d1q1',1),(1,'d1q2',1),(1,'d1q3',2),(1,'d1q4',2),(1,'d1q5',1),(1,'d1q6',1),(1,'d1q7',1),
  -- Day 2 (ED Endings)
  (2,'d5q1',1),(2,'d5q2',1),(2,'d5q3',2),(2,'d5q4',1),(2,'d5q5',1),(2,'d5q6',1),(2,'d5q7',1),
  -- Day 3
  (3,'d3q1',1),(3,'d3q2',1),(3,'d3q3',1),(3,'d3q4',2),(3,'d3q5',0),(3,'d3q6',0),(3,'d3q7',1),
  -- Day 4
  (4,'d4q1',1),(4,'d4q2',2),(4,'d4q3',0),(4,'d4q4',2),(4,'d4q5',1),(4,'d4q6',2),(4,'d4q7',1),
  -- Day 5
  (5,'d2q1',1),(5,'d2q2',2),(5,'d2q3',1)
ON CONFLICT (lesson_order, question_id) DO NOTHING;

-- ── 11. Remove sensitive data from course_config ──────────────────────────────
-- IMPORTANT: Run AFTER you have completed admin bootstrap (scripts/bootstrap-admin.js)
-- and AFTER students are migrated to Supabase Auth.
-- Uncomment when ready:
--
-- DELETE FROM public.course_config WHERE id = 'admin_cred';
-- DELETE FROM public.course_config WHERE id = 'el_settings';
-- UPDATE public.students SET password_hash = NULL WHERE password_hash IS NOT NULL;

-- ── Done ──────────────────────────────────────────────────────────────────────
-- Next steps:
--   1. Run scripts/bootstrap-admin.js to create admin Supabase Auth account
--   2. Run scripts/migrate-students.js to migrate student accounts
--   3. Deploy Edge Functions: tts, submit-quiz (+ update clever-api)
--   4. Set secrets: ELEVENLABS_API_KEY, BUNNY_TOKEN_KEY, BUNNY_LIBRARY_ID
--   5. Deploy updated index.html
--   6. Verify auth works for admin + students
--   7. Uncomment DELETE/UPDATE lines above
